### ISSUE TITLE
Inconsistent packages

### ISSUE THREAD

**Issue by niloc132** [gwtproject/gwt-callback#1]
As a rule, packages should only change from `com.google.gwt.$module` to `org.gwtproject.$module`, so that the first migration step is just a matter of rewriting those packages in a project, not actually going class-by-class and seeing where it was moved to.

As such, Callback belongs in gwt-core (see https://github.com/Vertispan/gwt-core/blob/master/src/main/java/org/gwtproject/core/client/Callback.java, that project is just coming online, still a work in progress), and AsyncCallback belongs in `org.gwtproject.user.client.rpc`. I certainly agree that is has no business being in `client`, but that is a great change to make in a later revision.

**Comment by metteo** [comment]
Agreed. Will make the adjustments soon.

**Comment by metteo** [comment]
@niloc132 it should be fine now.

**Comment by FrankHossfeld** [comment]
Done
